# Usar a imagem oficial do Node.js
FROM node:18

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos de dependências
COPY package*.json ./

# Instalar dependências
RUN npm install

# Instalar react-scripts globalmente para garantir a disponibilidade
RUN npm install -g react-scripts

# Copiar o restante do código da aplicação
COPY . .

# Construir a aplicação
RUN npm run build

# Rodar o servidor de desenvolvimento
CMD ["npm", "start"]